# Generated by Django 2.0.2 on 2018-03-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='office',
            table='office',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.AlterModelTable(
            name='projectmember',
            table='project_member',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
