# Generated by Django 2.0.2 on 2018-03-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
